sudo: required
service: 
  - docker

before_install:
  - docker build -t sahakyanvahan/docker-react -f Dockerfile.dev .

script:
  - docker run sahakyanvahan/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-750303711184"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
